// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: credit_card.proto

package creditcardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The field will contain credit card details in the format number:month/year:cvv:owner,
	// where the owner can be omitted.
	Data  []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Notes []byte `protobuf:"bytes,3,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
}

func (x *CreditCard) Reset() {
	*x = CreditCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credit_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCard) ProtoMessage() {}

func (x *CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_credit_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCard.ProtoReflect.Descriptor instead.
func (*CreditCard) Descriptor() ([]byte, []int) {
	return file_credit_card_proto_rawDescGZIP(), []int{0}
}

func (x *CreditCard) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CreditCard) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreditCard) GetNotes() []byte {
	if x != nil {
		return x.Notes
	}
	return nil
}

type AddCreditCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *CreditCard `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *AddCreditCardRequest) Reset() {
	*x = AddCreditCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credit_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCreditCardRequest) ProtoMessage() {}

func (x *AddCreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCreditCardRequest.ProtoReflect.Descriptor instead.
func (*AddCreditCardRequest) Descriptor() ([]byte, []int) {
	return file_credit_card_proto_rawDescGZIP(), []int{1}
}

func (x *AddCreditCardRequest) GetCard() *CreditCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCreditCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetCreditCardRequest) Reset() {
	*x = GetCreditCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credit_card_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditCardRequest) ProtoMessage() {}

func (x *GetCreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_card_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditCardRequest.ProtoReflect.Descriptor instead.
func (*GetCreditCardRequest) Descriptor() ([]byte, []int) {
	return file_credit_card_proto_rawDescGZIP(), []int{2}
}

func (x *GetCreditCardRequest) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

type UpdateCreditCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []byte                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Card *UpdateCreditCardRequest_CreditCard `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *UpdateCreditCardRequest) Reset() {
	*x = UpdateCreditCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credit_card_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCreditCardRequest) ProtoMessage() {}

func (x *UpdateCreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_card_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCreditCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCreditCardRequest) Descriptor() ([]byte, []int) {
	return file_credit_card_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCreditCardRequest) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateCreditCardRequest) GetCard() *UpdateCreditCardRequest_CreditCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type IndexCreditCardsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names [][]byte `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *IndexCreditCardsResponse) Reset() {
	*x = IndexCreditCardsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credit_card_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexCreditCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexCreditCardsResponse) ProtoMessage() {}

func (x *IndexCreditCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_card_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexCreditCardsResponse.ProtoReflect.Descriptor instead.
func (*IndexCreditCardsResponse) Descriptor() ([]byte, []int) {
	return file_credit_card_proto_rawDescGZIP(), []int{4}
}

func (x *IndexCreditCardsResponse) GetNames() [][]byte {
	if x != nil {
		return x.Names
	}
	return nil
}

type DeleteCreditCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteCreditCardRequest) Reset() {
	*x = DeleteCreditCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credit_card_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCreditCardRequest) ProtoMessage() {}

func (x *DeleteCreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_card_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCreditCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCreditCardRequest) Descriptor() ([]byte, []int) {
	return file_credit_card_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCreditCardRequest) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

// The CreditCard resource which replaces the resource on the server.
type UpdateCreditCardRequest_CreditCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  []byte `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Notes []byte `protobuf:"bytes,3,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
}

func (x *UpdateCreditCardRequest_CreditCard) Reset() {
	*x = UpdateCreditCardRequest_CreditCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credit_card_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCreditCardRequest_CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCreditCardRequest_CreditCard) ProtoMessage() {}

func (x *UpdateCreditCardRequest_CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_credit_card_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCreditCardRequest_CreditCard.ProtoReflect.Descriptor instead.
func (*UpdateCreditCardRequest_CreditCard) Descriptor() ([]byte, []int) {
	return file_credit_card_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpdateCreditCardRequest_CreditCard) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateCreditCardRequest_CreditCard) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateCreditCardRequest_CreditCard) GetNotes() []byte {
	if x != nil {
		return x.Notes
	}
	return nil
}

var File_credit_card_proto protoreflect.FileDescriptor

var file_credit_card_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72, 0x64, 0x2e,
	0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x59, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x14, 0x41, 0x64,
	0x64, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72,
	0x64, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xeb, 0x01,
	0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x45, 0x0a,
	0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04,
	0x63, 0x61, 0x72, 0x64, 0x1a, 0x75, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x02, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x88, 0x01, 0x01, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x18, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x2d, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xae, 0x03, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x12, 0x4c, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x23, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72, 0x64, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x4f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x23, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x63, 0x61,
	0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x52, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x26, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x53, 0x0a, 0x10, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x27, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x26, 0x2e,
	0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x1b, 0x5a,
	0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x63, 0x61, 0x72, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_credit_card_proto_rawDescOnce sync.Once
	file_credit_card_proto_rawDescData = file_credit_card_proto_rawDesc
)

func file_credit_card_proto_rawDescGZIP() []byte {
	file_credit_card_proto_rawDescOnce.Do(func() {
		file_credit_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_credit_card_proto_rawDescData)
	})
	return file_credit_card_proto_rawDescData
}

var file_credit_card_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_credit_card_proto_goTypes = []interface{}{
	(*CreditCard)(nil),                         // 0: creditcard.v1.CreditCard
	(*AddCreditCardRequest)(nil),               // 1: creditcard.v1.AddCreditCardRequest
	(*GetCreditCardRequest)(nil),               // 2: creditcard.v1.GetCreditCardRequest
	(*UpdateCreditCardRequest)(nil),            // 3: creditcard.v1.UpdateCreditCardRequest
	(*IndexCreditCardsResponse)(nil),           // 4: creditcard.v1.IndexCreditCardsResponse
	(*DeleteCreditCardRequest)(nil),            // 5: creditcard.v1.DeleteCreditCardRequest
	(*UpdateCreditCardRequest_CreditCard)(nil), // 6: creditcard.v1.UpdateCreditCardRequest.CreditCard
	(*emptypb.Empty)(nil),                      // 7: google.protobuf.Empty
}
var file_credit_card_proto_depIdxs = []int32{
	0, // 0: creditcard.v1.AddCreditCardRequest.card:type_name -> creditcard.v1.CreditCard
	6, // 1: creditcard.v1.UpdateCreditCardRequest.card:type_name -> creditcard.v1.UpdateCreditCardRequest.CreditCard
	1, // 2: creditcard.v1.CreditCardsVault.AddCreditCard:input_type -> creditcard.v1.AddCreditCardRequest
	2, // 3: creditcard.v1.CreditCardsVault.GetCreditCard:input_type -> creditcard.v1.GetCreditCardRequest
	3, // 4: creditcard.v1.CreditCardsVault.UpdateCreditCard:input_type -> creditcard.v1.UpdateCreditCardRequest
	7, // 5: creditcard.v1.CreditCardsVault.IndexCreditCards:input_type -> google.protobuf.Empty
	5, // 6: creditcard.v1.CreditCardsVault.DeleteCreditCard:input_type -> creditcard.v1.DeleteCreditCardRequest
	7, // 7: creditcard.v1.CreditCardsVault.AddCreditCard:output_type -> google.protobuf.Empty
	0, // 8: creditcard.v1.CreditCardsVault.GetCreditCard:output_type -> creditcard.v1.CreditCard
	7, // 9: creditcard.v1.CreditCardsVault.UpdateCreditCard:output_type -> google.protobuf.Empty
	4, // 10: creditcard.v1.CreditCardsVault.IndexCreditCards:output_type -> creditcard.v1.IndexCreditCardsResponse
	7, // 11: creditcard.v1.CreditCardsVault.DeleteCreditCard:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_credit_card_proto_init() }
func file_credit_card_proto_init() {
	if File_credit_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_credit_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credit_card_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCreditCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credit_card_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCreditCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credit_card_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCreditCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credit_card_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexCreditCardsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credit_card_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCreditCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credit_card_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCreditCardRequest_CreditCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_credit_card_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_credit_card_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_credit_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credit_card_proto_goTypes,
		DependencyIndexes: file_credit_card_proto_depIdxs,
		MessageInfos:      file_credit_card_proto_msgTypes,
	}.Build()
	File_credit_card_proto = out.File
	file_credit_card_proto_rawDesc = nil
	file_credit_card_proto_goTypes = nil
	file_credit_card_proto_depIdxs = nil
}
